/*
 * This file is generated by jOOQ.
 */
package org.mvnsearch.infrastructure.jooq.tables;


import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.mvnsearch.infrastructure.jooq.JooqSchema;
import org.mvnsearch.infrastructure.jooq.Keys;
import org.mvnsearch.infrastructure.jooq.tables.records.AuthorRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthorTable extends TableImpl<AuthorRecord> {

    private static final long serialVersionUID = -922827287;

    /**
     * The reference instance of <code>jooq.author</code>
     */
    public static final AuthorTable AUTHOR = new AuthorTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuthorRecord> getRecordType() {
        return AuthorRecord.class;
    }

    /**
     * The column <code>jooq.author.id</code>.
     */
    public final TableField<AuthorRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>jooq.author.first_name</code>.
     */
    public final TableField<AuthorRecord, String> FIRST_NAME = createField(DSL.name("first_name"), org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>jooq.author.last_name</code>.
     */
    public final TableField<AuthorRecord, String> LAST_NAME = createField(DSL.name("last_name"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>jooq.author.gender</code>.
     */
    public final TableField<AuthorRecord, String> GENDER = createField(DSL.name("gender"), org.jooq.impl.SQLDataType.VARCHAR(16), this, "");

    /**
     * The column <code>jooq.author.date_of_birth</code>.
     */
    public final TableField<AuthorRecord, LocalDate> DATE_OF_BIRTH = createField(DSL.name("date_of_birth"), org.jooq.impl.SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>jooq.author.year_of_birth</code>.
     */
    public final TableField<AuthorRecord, Integer> YEAR_OF_BIRTH = createField(DSL.name("year_of_birth"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>jooq.author.distinguished</code>.
     */
    public final TableField<AuthorRecord, Integer> DISTINGUISHED = createField(DSL.name("distinguished"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>jooq.author</code> table reference
     */
    public AuthorTable() {
        this(DSL.name("author"), null);
    }

    /**
     * Create an aliased <code>jooq.author</code> table reference
     */
    public AuthorTable(String alias) {
        this(DSL.name(alias), AUTHOR);
    }

    /**
     * Create an aliased <code>jooq.author</code> table reference
     */
    public AuthorTable(Name alias) {
        this(alias, AUTHOR);
    }

    private AuthorTable(Name alias, Table<AuthorRecord> aliased) {
        this(alias, aliased, null);
    }

    private AuthorTable(Name alias, Table<AuthorRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> AuthorTable(Table<O> child, ForeignKey<O, AuthorRecord> key) {
        super(child, key, AUTHOR);
    }

    @Override
    public Schema getSchema() {
        return JooqSchema.JOOQ;
    }

    @Override
    public Identity<AuthorRecord, Integer> getIdentity() {
        return Keys.IDENTITY_AUTHOR;
    }

    @Override
    public UniqueKey<AuthorRecord> getPrimaryKey() {
        return Keys.KEY_AUTHOR_PRIMARY;
    }

    @Override
    public List<UniqueKey<AuthorRecord>> getKeys() {
        return Arrays.<UniqueKey<AuthorRecord>>asList(Keys.KEY_AUTHOR_PRIMARY);
    }

    @Override
    public AuthorTable as(String alias) {
        return new AuthorTable(DSL.name(alias), this);
    }

    @Override
    public AuthorTable as(Name alias) {
        return new AuthorTable(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthorTable rename(String name) {
        return new AuthorTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthorTable rename(Name name) {
        return new AuthorTable(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, String, LocalDate, Integer, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
