/*
 * This file is generated by jOOQ.
 */
package org.mvnsearch.infrastructure.jooq.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row1;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.mvnsearch.infrastructure.jooq.Indexes;
import org.mvnsearch.infrastructure.jooq.JooqSchema;
import org.mvnsearch.infrastructure.jooq.Keys;
import org.mvnsearch.infrastructure.jooq.tables.records.BookStoreRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookStoreTable extends TableImpl<BookStoreRecord> {

    private static final long serialVersionUID = 1273811818;

    /**
     * The reference instance of <code>jooq.book_store</code>
     */
    public static final BookStoreTable BOOK_STORE = new BookStoreTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BookStoreRecord> getRecordType() {
        return BookStoreRecord.class;
    }

    /**
     * The column <code>jooq.book_store.name</code>.
     */
    public final TableField<BookStoreRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(400).nullable(false), this, "");

    /**
     * Create a <code>jooq.book_store</code> table reference
     */
    public BookStoreTable() {
        this(DSL.name("book_store"), null);
    }

    /**
     * Create an aliased <code>jooq.book_store</code> table reference
     */
    public BookStoreTable(String alias) {
        this(DSL.name(alias), BOOK_STORE);
    }

    /**
     * Create an aliased <code>jooq.book_store</code> table reference
     */
    public BookStoreTable(Name alias) {
        this(alias, BOOK_STORE);
    }

    private BookStoreTable(Name alias, Table<BookStoreRecord> aliased) {
        this(alias, aliased, null);
    }

    private BookStoreTable(Name alias, Table<BookStoreRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> BookStoreTable(Table<O> child, ForeignKey<O, BookStoreRecord> key) {
        super(child, key, BOOK_STORE);
    }

    @Override
    public Schema getSchema() {
        return JooqSchema.JOOQ;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.BOOK_STORE_NAME);
    }

    @Override
    public List<UniqueKey<BookStoreRecord>> getKeys() {
        return Arrays.<UniqueKey<BookStoreRecord>>asList(Keys.KEY_BOOK_STORE_NAME);
    }

    @Override
    public BookStoreTable as(String alias) {
        return new BookStoreTable(DSL.name(alias), this);
    }

    @Override
    public BookStoreTable as(Name alias) {
        return new BookStoreTable(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BookStoreTable rename(String name) {
        return new BookStoreTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BookStoreTable rename(Name name) {
        return new BookStoreTable(name, null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }
}
