/**
 * This class is generated by jOOQ
 */
package org.mvnsearch.infrastructure.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.mvnsearch.infrastructure.jooq.JooqTable;
import org.mvnsearch.infrastructure.jooq.Keys;
import org.mvnsearch.infrastructure.jooq.tables.records.BookRecordTable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookTable extends TableImpl<BookRecordTable> {

	private static final long serialVersionUID = 1629629806;

	/**
	 * The reference instance of <code>jooq.book</code>
	 */
	public static final BookTable BOOK = new BookTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<BookRecordTable> getRecordType() {
		return BookRecordTable.class;
	}

	/**
	 * The column <code>jooq.book.id</code>.
	 */
	public final TableField<BookRecordTable, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>jooq.book.author_id</code>.
	 */
	public final TableField<BookRecordTable, Integer> AUTHOR_ID = createField("author_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>jooq.book.title</code>.
	 */
	public final TableField<BookRecordTable, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(400), this, "");

	/**
	 * The column <code>jooq.book.published_in</code>.
	 */
	public final TableField<BookRecordTable, Integer> PUBLISHED_IN = createField("published_in", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>jooq.book.language_id</code>.
	 */
	public final TableField<BookRecordTable, Integer> LANGUAGE_ID = createField("language_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>jooq.book</code> table reference
	 */
	public BookTable() {
		this("book", null);
	}

	/**
	 * Create an aliased <code>jooq.book</code> table reference
	 */
	public BookTable(String alias) {
		this(alias, BOOK);
	}

	private BookTable(String alias, Table<BookRecordTable> aliased) {
		this(alias, aliased, null);
	}

	private BookTable(String alias, Table<BookRecordTable> aliased, Field<?>[] parameters) {
		super(alias, JooqTable.JOOQ, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<BookRecordTable> getPrimaryKey() {
		return Keys.KEY_BOOK_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<BookRecordTable>> getKeys() {
		return Arrays.<UniqueKey<BookRecordTable>>asList(Keys.KEY_BOOK_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BookTable as(String alias) {
		return new BookTable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public BookTable rename(String name) {
		return new BookTable(name, null);
	}
}
