/**
 * This class is generated by jOOQ
 */
package org.mvnsearch.infrastructure.jooq.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;
import org.mvnsearch.infrastructure.jooq.JooqTable;
import org.mvnsearch.infrastructure.jooq.tables.records.BookStoreRecordTable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookStoreTable extends TableImpl<BookStoreRecordTable> {

	private static final long serialVersionUID = 473943960;

	/**
	 * The reference instance of <code>jooq.book_store</code>
	 */
	public static final BookStoreTable BOOK_STORE = new BookStoreTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<BookStoreRecordTable> getRecordType() {
		return BookStoreRecordTable.class;
	}

	/**
	 * The column <code>jooq.book_store.name</code>.
	 */
	public final TableField<BookStoreRecordTable, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(400), this, "");

	/**
	 * Create a <code>jooq.book_store</code> table reference
	 */
	public BookStoreTable() {
		this("book_store", null);
	}

	/**
	 * Create an aliased <code>jooq.book_store</code> table reference
	 */
	public BookStoreTable(String alias) {
		this(alias, BOOK_STORE);
	}

	private BookStoreTable(String alias, Table<BookStoreRecordTable> aliased) {
		this(alias, aliased, null);
	}

	private BookStoreTable(String alias, Table<BookStoreRecordTable> aliased, Field<?>[] parameters) {
		super(alias, JooqTable.JOOQ, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BookStoreTable as(String alias) {
		return new BookStoreTable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public BookStoreTable rename(String name) {
		return new BookStoreTable(name, null);
	}
}
