/*
 * This file is generated by jOOQ.
 */
package org.mvnsearch.infrastructure.jooq.tables.records;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

import javax.annotation.Nullable;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;
import org.mvnsearch.infrastructure.jooq.tables.BookToBookStore;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "book_to_book_store",
    schema = "jooq"
)
public class BookToBookStoreRecord extends UpdatableRecordImpl<BookToBookStoreRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>jooq.book_to_book_store.name</code>.
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>jooq.book_to_book_store.name</code>.
     */
    @Column(name = "name", nullable = false, length = 400)
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>jooq.book_to_book_store.book_id</code>.
     */
    public void setBookId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>jooq.book_to_book_store.book_id</code>.
     */
    @Column(name = "book_id", nullable = false)
    public Integer getBookId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>jooq.book_to_book_store.stock</code>.
     */
    public void setStock(@Nullable Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>jooq.book_to_book_store.stock</code>.
     */
    @Column(name = "stock")
    @Nullable
    public Integer getStock() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookToBookStoreRecord
     */
    public BookToBookStoreRecord() {
        super(BookToBookStore.BOOK_TO_BOOK_STORE);
    }

    /**
     * Create a detached, initialised BookToBookStoreRecord
     */
    public BookToBookStoreRecord(String name, Integer bookId, @Nullable Integer stock) {
        super(BookToBookStore.BOOK_TO_BOOK_STORE);

        setName(name);
        setBookId(bookId);
        setStock(stock);
        resetTouchedOnNotNull();
    }
}
