/*
 * This file is generated by jOOQ.
 */
package org.mvnsearch.infrastructure.jooq.tables.records;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import org.jooq.impl.TableRecordImpl;
import org.mvnsearch.infrastructure.jooq.tables.BookStore;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "book_store",
    schema = "jooq",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_book_store_name", columnNames = { "name" })
    }
)
public class BookStoreRecord extends TableRecordImpl<BookStoreRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>jooq.book_store.name</code>.
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>jooq.book_store.name</code>.
     */
    @Column(name = "name", nullable = false, length = 400)
    public String getName() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookStoreRecord
     */
    public BookStoreRecord() {
        super(BookStore.BOOK_STORE);
    }

    /**
     * Create a detached, initialised BookStoreRecord
     */
    public BookStoreRecord(String name) {
        super(BookStore.BOOK_STORE);

        setName(name);
        resetTouchedOnNotNull();
    }
}
