/**
 * This class is generated by jOOQ
 */
package org.mvnsearch.jooq.db;


import javax.annotation.Generated;

import org.mvnsearch.jooq.db.tables.Author;
import org.mvnsearch.jooq.db.tables.Book;
import org.mvnsearch.jooq.db.tables.BookStore;
import org.mvnsearch.jooq.db.tables.BookToBookStore;
import org.mvnsearch.jooq.db.tables.Language;


/**
 * Convenience access to all tables in jooq
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table jooq.author
	 */
	public static final Author AUTHOR = org.mvnsearch.jooq.db.tables.Author.AUTHOR;

	/**
	 * The table jooq.book
	 */
	public static final Book BOOK = org.mvnsearch.jooq.db.tables.Book.BOOK;

	/**
	 * The table jooq.book_store
	 */
	public static final BookStore BOOK_STORE = org.mvnsearch.jooq.db.tables.BookStore.BOOK_STORE;

	/**
	 * The table jooq.book_to_book_store
	 */
	public static final BookToBookStore BOOK_TO_BOOK_STORE = org.mvnsearch.jooq.db.tables.BookToBookStore.BOOK_TO_BOOK_STORE;

	/**
	 * The table jooq.language
	 */
	public static final Language LANGUAGE = org.mvnsearch.jooq.db.tables.Language.LANGUAGE;
}
