/*
 * This file is generated by jOOQ.
 */
package org.mvnsearch.infrastructure.jooq;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;
import org.mvnsearch.infrastructure.jooq.tables.BookStoreTable;


/**
 * A class modelling indexes of tables of the <code>jooq</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index BOOK_STORE_NAME = Indexes0.BOOK_STORE_NAME;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index BOOK_STORE_NAME = Internal.createIndex("name", BookStoreTable.BOOK_STORE, new OrderField[] { BookStoreTable.BOOK_STORE.NAME }, true);
    }
}
