/*
 * This file is generated by jOOQ.
 */
package org.mvnsearch.infrastructure.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;
import org.mvnsearch.infrastructure.jooq.tables.Author;
import org.mvnsearch.infrastructure.jooq.tables.Book;
import org.mvnsearch.infrastructure.jooq.tables.BookStore;
import org.mvnsearch.infrastructure.jooq.tables.BookToBookStore;
import org.mvnsearch.infrastructure.jooq.tables.Language;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Jooq extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>jooq</code>
     */
    public static final Jooq JOOQ = new Jooq();

    /**
     * The table <code>jooq.author</code>.
     */
    public final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>jooq.book</code>.
     */
    public final Book BOOK = Book.BOOK;

    /**
     * The table <code>jooq.book_store</code>.
     */
    public final BookStore BOOK_STORE = BookStore.BOOK_STORE;

    /**
     * The table <code>jooq.book_to_book_store</code>.
     */
    public final BookToBookStore BOOK_TO_BOOK_STORE = BookToBookStore.BOOK_TO_BOOK_STORE;

    /**
     * The table <code>jooq.language</code>.
     */
    public final Language LANGUAGE = Language.LANGUAGE;

    /**
     * No further instances allowed
     */
    private Jooq() {
        super(DSL.name("jooq"), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Author.AUTHOR,
            Book.BOOK,
            BookStore.BOOK_STORE,
            BookToBookStore.BOOK_TO_BOOK_STORE,
            Language.LANGUAGE
        );
    }
}
