/**
 * This class is generated by jOOQ
 */
package org.mvnsearch.infrastructure.jooq;


import javax.annotation.Generated;

import org.mvnsearch.infrastructure.jooq.tables.AuthorTable;
import org.mvnsearch.infrastructure.jooq.tables.BookStoreTable;
import org.mvnsearch.infrastructure.jooq.tables.BookTable;
import org.mvnsearch.infrastructure.jooq.tables.BookToBookStoreTable;
import org.mvnsearch.infrastructure.jooq.tables.LanguageTable;


/**
 * Convenience access to all tables in jooq
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table jooq.author
	 */
	public static final AuthorTable AUTHOR = org.mvnsearch.infrastructure.jooq.tables.AuthorTable.AUTHOR;

	/**
	 * The table jooq.book
	 */
	public static final BookTable BOOK = org.mvnsearch.infrastructure.jooq.tables.BookTable.BOOK;

	/**
	 * The table jooq.book_store
	 */
	public static final BookStoreTable BOOK_STORE = org.mvnsearch.infrastructure.jooq.tables.BookStoreTable.BOOK_STORE;

	/**
	 * The table jooq.book_to_book_store
	 */
	public static final BookToBookStoreTable BOOK_TO_BOOK_STORE = org.mvnsearch.infrastructure.jooq.tables.BookToBookStoreTable.BOOK_TO_BOOK_STORE;

	/**
	 * The table jooq.language
	 */
	public static final LanguageTable LANGUAGE = org.mvnsearch.infrastructure.jooq.tables.LanguageTable.LANGUAGE;
}
