/*
 * This file is generated by jOOQ.
 */
package org.mvnsearch.infrastructure.jooq;


import org.mvnsearch.infrastructure.jooq.tables.AuthorTable;
import org.mvnsearch.infrastructure.jooq.tables.BookStoreTable;
import org.mvnsearch.infrastructure.jooq.tables.BookTable;
import org.mvnsearch.infrastructure.jooq.tables.BookToBookStoreTable;
import org.mvnsearch.infrastructure.jooq.tables.LanguageTable;


/**
 * Convenience access to all tables in jooq.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>jooq.author</code>.
     */
    public static final AuthorTable AUTHOR = AuthorTable.AUTHOR;

    /**
     * The table <code>jooq.book</code>.
     */
    public static final BookTable BOOK = BookTable.BOOK;

    /**
     * The table <code>jooq.book_store</code>.
     */
    public static final BookStoreTable BOOK_STORE = BookStoreTable.BOOK_STORE;

    /**
     * The table <code>jooq.book_to_book_store</code>.
     */
    public static final BookToBookStoreTable BOOK_TO_BOOK_STORE = BookToBookStoreTable.BOOK_TO_BOOK_STORE;

    /**
     * The table <code>jooq.language</code>.
     */
    public static final LanguageTable LANGUAGE = LanguageTable.LANGUAGE;
}
