/*
 * This file is generated by jOOQ.
 */
package org.mvnsearch.infrastructure.jooq;


import org.mvnsearch.infrastructure.jooq.tables.Author;
import org.mvnsearch.infrastructure.jooq.tables.Book;
import org.mvnsearch.infrastructure.jooq.tables.BookStore;
import org.mvnsearch.infrastructure.jooq.tables.BookToBookStore;
import org.mvnsearch.infrastructure.jooq.tables.Language;


/**
 * Convenience access to all tables in jooq.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>jooq.author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>jooq.book</code>.
     */
    public static final Book BOOK = Book.BOOK;

    /**
     * The table <code>jooq.book_store</code>.
     */
    public static final BookStore BOOK_STORE = BookStore.BOOK_STORE;

    /**
     * The table <code>jooq.book_to_book_store</code>.
     */
    public static final BookToBookStore BOOK_TO_BOOK_STORE = BookToBookStore.BOOK_TO_BOOK_STORE;

    /**
     * The table <code>jooq.language</code>.
     */
    public static final Language LANGUAGE = Language.LANGUAGE;
}
